### PR TITLE
fix: remove validation of registrationform

### PR DESCRIPTION
**Pull request by losolio**

### CODE REVIEW

**Comment by LovelyXinf** [comment]
Hi , I am Lucas,
I check your PR now

**Comment by LovelyXinf** [comment]
I can do it well into 3hours.

**Comment by qalb110** [comment]
Hey, 

I am available now for a quick fix, We can do a meeting as well.https://www.upwork.com/freelancers/~015b73025086ec0199 Please send invite

**Comment by LovelyXinf** [comment]
Can we meeting on telegram or skype or Gmail
Skype:live:.cid.f6feb55d13d5473b
Telegram:https://t.me/SilverDiamond0828
Gmail: lovelyman0215@gmail.com

**Comment by LovelyXinf** [comment]
Congratulations!

**Pull request merged**
