### PR TITLE
Issues/436 api for registration of particiants

### PR DESCRIPTION
**Pull request by andy-a-o**
API documentation to be provided below.

All API methods are covered with tests.

Some refactoring was made so the resulting PR is quite large. Sorry for that...
In particular:

 - Most of the (old) `RegistrationService` methods were marked as `Obsolete` with the references to the new services.
 - Integration API infrastructure moved to the shared `TestAbstractions` project.
 - `Eventuras.Services.Exceptions` namespace enhanced with `DuplicateException`. All service-layer exceptions are handled and converted to HTTP status codes (not found, forbidden, conflict etc).

### CODE REVIEW

**Comment by andy-a-o** [comment]
=== List registrations

```
GET /v3/registrations?page=1&count=100
```

Parameters:

1. page (`int`) `1`-based page index. Default is `1`.
2. count (`int`) MAX is `100`. Default is `100`.

Return values:

```
{
	page: 1,
	count: 100,
	total: 1000,
	pages: 10,
	data: [
		registrationId: 199,
		eventId: 3,
		userId: "01234-...",
		status: 1,
		type: 1,
		notes: ""
	]
}
```

The returned list is filtered for the authenticated user.
Regular users can list own registrations only.
Org admin can list registrations related to the current org.
System admin and super admin can read all registrations.

Error status codes:

`400` (Bad request) - invalid query parameter.
`401` (Unauthorized) - valid JWT required.

===

**Comment by andy-a-o** [comment]
### Create new registration

```
POST /v3/registrations
```

Post body:

```json
{
	"eventId": 10023,
	"userId": "123...",
	"customer": {
		"name": "John Doe",
		"email": "test@email.com",
		"city": "...",
		"zip": "...",
		"country": "...",
		"vatNumber": "...",
		"invoiceReference": "..."
	},
	"notes": "...",
	"type": 2,
	"paymentMethod": 3
}
```

Note: `"customer"`, `"notes"`, `"type"` and `"paymentMethod"` properties are available for admins only.

Error status codes:

`400` (Bad request) - invalid POST body.
`401` (Unauthorized) - valid JWT required.
`403` (Forbidden) - regular users are not allowed to create registrations for other users; admins can't create registration to the events from another organization.
`404` (NotFound) - user or event not found.

**Comment by andy-a-o** [comment]
### Update registration

```
PUT /v3/registrations/{id}
```

Post body:

```json
{
	"customer": {
		"name": "John Doe",
		"email": "test@email.com",
		"city": "...",
		"zip": "...",
		"country": "...",
		"vatNumber": "...",
		"invoiceReference": "..."
	},
	"notes": "...",
	"type": 2,
	"paymentMethod": 3
}
```

Note: API is available for admins only.

Error status codes:

`400` (Bad request) - invalid POST body.
`401` (Unauthorized) - valid JWT required.
`403` (Forbidden) - admins can't update registration to the events from another organization.
`404` (NotFound) - registration not found.

**Comment by andy-a-o** [comment]
### Cancel registration

```
DELETE /v3/registrations/{id}
```

Note: API is available for admins only.

Error status codes:

`400` (Bad request) - invalid POST body.
`401` (Unauthorized) - valid JWT required.
`403` (Forbidden) - admins can't cancel registration to the events from another organization.
`404` (NotFound) - registration not found.

**Comment by andy-a-o** [comment]
### Create order for registration

```
POST /v3/registrations/{id}/orders
```

Post body:

```json
{
	"items": [{
		"productId": 13,
		"productVariantId": 245,
		"quantity": 1
	}]
}
```

Note: API is available for admins only.

Response:

```json
{
	"orderId": 123,
	"items": [{
		"product": {
			"productId": 13,
			"name": "Test",
			"description": "...",
			"more": "...",
			"price": 234.22,
			"vatPercent": 13
		},
		"productVariant": {
			"productVariantId": 245,
			"name": "...",
			"description": "...",
			"price": 333.22,
		},
		"quantity": 1
	}]
}
```

Error status codes:

`400` (Bad request) - invalid POST body.
`401` (Unauthorized) - valid JWT required.
`403` (Forbidden) - admins can't access registration to the events from another organization.
`404` (NotFound) - registration not found.

**Review by losolio — APPROVED** [review]

**Pull request merged**
